server:
  port: 8087
spring:
  # profiles:
  # active: @spring.profiles.active@
  datasource:
    url: jdbc:postgresql://postgres-sql:5432/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret-key: 7638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B6150645267556B5870

fake-api:
  store:
    url: https://fakestoreapi.com/products
springdoc:
  default-produces-media-type: application/json
