name: Banqueapi CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and Deploy Spring boot API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Compile
        run: mvn clean compile

      - name: Unit tests
        run: mvn clean test



      - name: Build the API
        run: mvn clean package

      - name: Get the date
        id: date
        run: echo "::set-output name=date::$(date +'%-m%d%H%M')"



      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bank_api:${{ steps.date.outputs.date }}

